### ISSUE TITLE
hacktoberfest-swag has been excluded from HF by DigitalOcean

### ISSUE THREAD

**Issue by SoftCreatR** [benbarth/hacktoberfest-swag#217]
Hello,

it has just come to my attention, that this repository has been excluded from HF by DigitalOcean. So, unfortunately, __contributions in this repository do not count towards your contributions goal for the event__.

I've contacted @mattipv4 regarding this issue. He answered me, that this repo has been reported multiple times for not following the values of Hacktoberfest.

I've requested a re-review, because this is absolutely not a "I just make 5 pull requests and grab a shirt" repo. It might have been in the past, but things have changed over time.

**Comment by MattIPv4** [comment]
Hey,

Thanks for flagging this.

Whilst many folks in our community have reported this repository as they feel it doesn't follow the values of Hacktoberfest, I suspect this might be more due to the nature of the repo (tracking swag opportunities) rather than the actual PRs happening in the repo -- the community (rightly so) seem to be very keen this year to remind folks that Hacktoberfest is about making valuable contributions to open source, not about getting some swag.

I've taken a look through the repo here, and whilst the community has reported it many times and I get that this repo definitely focuses on the swag of Hacktoberfest, y'all seem to have a good handle on legitimate vs spam pull requests, so I'll remove the exclusion on this repo for now 👍 

Matt.

**Comment by SoftCreatR** [comment]
Thank you very much, @MattIPv4 :octocat:

**Comment by SoftCreatR** [comment]
@benbarth
